from __future__ import annotations

import pyarrow as pa

from ..contracts import DECIMAL_U64

KERNEL_OBSERVATION_SCHEMA_ID = "joshi.analysis.marked-response-observation/v1"
KERNEL_OBSERVATION_SCHEMA = pa.schema(
    [
        pa.field("kernel_observation_id", pa.string(), nullable=False),
        pa.field("event_id", pa.string(), nullable=False),
        pa.field("event_time_status", pa.string(), nullable=False),
        pa.field("choice_context_status", pa.string(), nullable=False),
        pa.field("decision_id", pa.string(), nullable=True),
        pa.field("choice_set_id", pa.string(), nullable=True),
        pa.field("scene_id", pa.string(), nullable=True),
        pa.field("scene_view_digest", pa.string(), nullable=True),
        pa.field("universe_digest", pa.string(), nullable=True),
        pa.field("candidate_id", pa.string(), nullable=False),
        pa.field("caller_attribution_status", pa.string(), nullable=False),
        pa.field("caller_identity_version_id", pa.string(), nullable=True),
        pa.field("caller_wallet_id", pa.string(), nullable=True),
        pa.field("caller_class", pa.string(), nullable=True),
        pa.field("mark_family", pa.string(), nullable=False),
        pa.field("mark_direction", pa.string(), nullable=True),
        pa.field("mark_size_status", pa.string(), nullable=False),
        pa.field("mark_size_bucket", pa.string(), nullable=True),
        pa.field("mark_size_atoms", DECIMAL_U64, nullable=True),
        pa.field("mark_asset_id", pa.string(), nullable=True),
        pa.field("context_status", pa.string(), nullable=False),
        pa.field("territory_id", pa.string(), nullable=True),
        pa.field("territory_version_id", pa.string(), nullable=True),
        pa.field("community_id", pa.string(), nullable=True),
        pa.field("community_version_id", pa.string(), nullable=True),
        pa.field("venue_id", pa.string(), nullable=True),
        pa.field("lifecycle_state", pa.string(), nullable=True),
        pa.field("lifecycle_version_id", pa.string(), nullable=True),
        pa.field("regime_topology_status", pa.string(), nullable=False),
        pa.field("regime_epoch", pa.string(), nullable=True),
        pa.field("regime_version_id", pa.string(), nullable=True),
        pa.field("topology_epoch", pa.string(), nullable=True),
        pa.field("topology_version_id", pa.string(), nullable=True),
        pa.field("event_time", pa.timestamp("us", tz="UTC"), nullable=False),
        pa.field("event_valid_lower", pa.timestamp("us", tz="UTC"), nullable=False),
        pa.field("event_valid_upper", pa.timestamp("us", tz="UTC"), nullable=False),
        pa.field("event_slot_lower", pa.int64(), nullable=True),
        pa.field("event_slot_upper", pa.int64(), nullable=True),
        pa.field("event_available_at", pa.timestamp("us", tz="UTC"), nullable=False),
        pa.field("context_valid_lower", pa.timestamp("us", tz="UTC"), nullable=True),
        pa.field("context_valid_upper", pa.timestamp("us", tz="UTC"), nullable=True),
        pa.field("context_available_at", pa.timestamp("us", tz="UTC"), nullable=True),
        pa.field("context_retracted_at", pa.timestamp("us", tz="UTC"), nullable=True),
        pa.field("information_cutoff", pa.timestamp("us", tz="UTC"), nullable=False),
        pa.field("response_time", pa.timestamp("us", tz="UTC"), nullable=False),
        pa.field("response_available_at", pa.timestamp("us", tz="UTC"), nullable=False),
        pa.field("horizon_us", pa.int64(), nullable=False),
        pa.field("observable_kind", pa.string(), nullable=False),
        pa.field("response_value", pa.int64(), nullable=True),
        pa.field("response_unit", pa.string(), nullable=False),
        pa.field("coverage_status", pa.string(), nullable=False),
        pa.field("coverage_scope_id", pa.string(), nullable=False),
        pa.field("coverage_window_id", pa.string(), nullable=True),
        pa.field("coverage_gap_id", pa.string(), nullable=True),
        pa.field("available_commit_seq", pa.int64(), nullable=False),
    ]
)

KERNEL_CHOICE_MEMBER_SCHEMA = pa.schema(
    [
        pa.field("decision_id", pa.string(), nullable=False),
        pa.field("choice_set_id", pa.string(), nullable=False),
        pa.field("candidate_id", pa.string(), nullable=False),
        pa.field("set_kind", pa.string(), nullable=False),
        pa.field("source_rank", pa.int32(), nullable=False),
        pa.field("universe_digest", pa.string(), nullable=False),
        pa.field("available_at", pa.timestamp("us", tz="UTC"), nullable=False),
    ]
)

RISK_COHORT_SCHEMA = pa.schema(
    [
        pa.field("cohort_id", pa.string(), nullable=False),
        pa.field("choice_context_status", pa.string(), nullable=False),
        pa.field("decision_id", pa.string(), nullable=True),
        pa.field("choice_set_id", pa.string(), nullable=True),
        pa.field("universe_digest", pa.string(), nullable=True),
        pa.field("candidate_id", pa.string(), nullable=False),
        pa.field("caller_attribution_status", pa.string(), nullable=False),
        pa.field("caller_class", pa.string(), nullable=True),
        pa.field("territory_id", pa.string(), nullable=True),
        pa.field("territory_version_id", pa.string(), nullable=True),
        pa.field("regime_topology_status", pa.string(), nullable=False),
        pa.field("regime_epoch", pa.string(), nullable=True),
        pa.field("regime_version_id", pa.string(), nullable=True),
        pa.field("topology_epoch", pa.string(), nullable=True),
        pa.field("topology_version_id", pa.string(), nullable=True),
        pa.field("anchor_time", pa.timestamp("us", tz="UTC"), nullable=False),
        pa.field("anchor_slot", pa.int64(), nullable=True),
        pa.field("anchor_available_at", pa.timestamp("us", tz="UTC"), nullable=False),
        pa.field("context_valid_lower", pa.timestamp("us", tz="UTC"), nullable=True),
        pa.field("context_valid_upper", pa.timestamp("us", tz="UTC"), nullable=True),
        pa.field("context_available_at", pa.timestamp("us", tz="UTC"), nullable=True),
        pa.field("context_retracted_at", pa.timestamp("us", tz="UTC"), nullable=True),
        pa.field("risk_entry_time", pa.timestamp("us", tz="UTC"), nullable=False),
        pa.field("risk_exit_time", pa.timestamp("us", tz="UTC"), nullable=False),
        pa.field("horizon_us", pa.int64(), nullable=False),
        pa.field("event_kind", pa.string(), nullable=True),
        pa.field("event_time", pa.timestamp("us", tz="UTC"), nullable=True),
        pa.field("event_time_lower", pa.timestamp("us", tz="UTC"), nullable=True),
        pa.field("event_time_upper", pa.timestamp("us", tz="UTC"), nullable=True),
        pa.field("outcome_known_at", pa.timestamp("us", tz="UTC"), nullable=False),
        pa.field("right_censored", pa.bool_(), nullable=False),
        pa.field("censoring_kind", pa.string(), nullable=False),
        pa.field("censoring_reason", pa.string(), nullable=True),
        pa.field("coverage_status", pa.string(), nullable=False),
        pa.field("coverage_window_id", pa.string(), nullable=True),
        pa.field("coverage_gap_id", pa.string(), nullable=True),
    ]
)

KERNEL_ESTIMATE_SCHEMA_ID = "joshi.analysis.marked-response-kernel/v1"
KERNEL_ESTIMATE_SCHEMA = pa.schema(
    [
        pa.field("kernel_estimate_occurrence_id", pa.string(), nullable=False),
        pa.field("kernel_estimate_digest", pa.string(), nullable=False),
        pa.field("estimator_id", pa.string(), nullable=False),
        pa.field("estimator_version", pa.string(), nullable=False),
        pa.field("estimator_configuration_digest", pa.string(), nullable=False),
        pa.field("input_snapshot_id", pa.string(), nullable=False),
        pa.field("input_logical_digest", pa.string(), nullable=False),
        pa.field("training_lower_available_at", pa.timestamp("us", tz="UTC"), nullable=False),
        pa.field("fit_cutoff", pa.timestamp("us", tz="UTC"), nullable=False),
        pa.field("maximum_training_available_at", pa.timestamp("us", tz="UTC"), nullable=False),
        pa.field("as_of_commit_seq", pa.int64(), nullable=False),
        pa.field("caller_class", pa.string(), nullable=True),
        pa.field("mark_family", pa.string(), nullable=False),
        pa.field("mark_direction", pa.string(), nullable=True),
        pa.field("mark_size_bucket", pa.string(), nullable=True),
        pa.field("context_key", pa.string(), nullable=False),
        pa.field("interaction_key", pa.string(), nullable=False),
        pa.field("regime_epoch", pa.string(), nullable=False),
        pa.field("topology_epoch", pa.string(), nullable=False),
        pa.field("horizon_us", pa.int64(), nullable=False),
        pa.field("observable_kind", pa.string(), nullable=False),
        pa.field("response_unit", pa.string(), nullable=False),
        pa.field("estimate", pa.float64(), nullable=True),
        pa.field("standard_error", pa.float64(), nullable=True),
        pa.field("interval_lower", pa.float64(), nullable=True),
        pa.field("interval_upper", pa.float64(), nullable=True),
        pa.field("uncertainty_method", pa.string(), nullable=False),
        pa.field("event_count", pa.int64(), nullable=False),
        pa.field("wallet_count", pa.int64(), nullable=False),
        pa.field("effective_sample_size", pa.float64(), nullable=False),
        pa.field("observed_count", pa.int64(), nullable=False),
        pa.field("gap_count", pa.int64(), nullable=False),
        pa.field("coverage_ratio_ppm", pa.int64(), nullable=False),
        pa.field("coverage_window_ids", pa.list_(pa.string()), nullable=False),
        pa.field("coverage_gap_ids", pa.list_(pa.string()), nullable=False),
        pa.field("context_event_count", pa.int64(), nullable=False),
        pa.field("mark_share_ppm", pa.int64(), nullable=False),
        pa.field("overlap_status", pa.string(), nullable=False),
        pa.field("nonstationarity_reference_epoch", pa.string(), nullable=True),
        pa.field("nonstationarity_delta", pa.float64(), nullable=True),
        pa.field("topology_boundary_status", pa.string(), nullable=False),
        pa.field("claim_scope", pa.string(), nullable=False),
    ]
)

CANDIDATE_DIAGNOSTIC_SCHEMA_ID = "joshi.analysis.response-model-candidate-diagnostic/v1"
CANDIDATE_DIAGNOSTIC_SCHEMA = pa.schema(
    [
        pa.field("diagnostic_occurrence_id", pa.string(), nullable=False),
        pa.field("diagnostic_digest", pa.string(), nullable=False),
        pa.field("diagnostic_family", pa.string(), nullable=False),
        pa.field("estimator_configuration_digest", pa.string(), nullable=False),
        pa.field("input_snapshot_id", pa.string(), nullable=False),
        pa.field("input_logical_digest", pa.string(), nullable=False),
        pa.field("target_kind", pa.string(), nullable=False),
        pa.field("context_key", pa.string(), nullable=False),
        pa.field("regime_epoch", pa.string(), nullable=False),
        pa.field("topology_epoch", pa.string(), nullable=False),
        pa.field("horizon_us", pa.int64(), nullable=False),
        pa.field("estimate", pa.float64(), nullable=False),
        pa.field("interval_lower", pa.float64(), nullable=False),
        pa.field("interval_upper", pa.float64(), nullable=False),
        pa.field("event_count", pa.int64(), nullable=False),
        pa.field("censored_count", pa.int64(), nullable=False),
        pa.field("coverage_ratio_ppm", pa.int64(), nullable=False),
        pa.field("coverage_window_ids", pa.list_(pa.string()), nullable=False),
        pa.field("coverage_gap_ids", pa.list_(pa.string()), nullable=False),
        pa.field("fit_cutoff", pa.timestamp("us", tz="UTC"), nullable=False),
        pa.field("maximum_training_available_at", pa.timestamp("us", tz="UTC"), nullable=False),
        pa.field("assumptions", pa.string(), nullable=False),
        pa.field("claim_scope", pa.string(), nullable=False),
    ]
)

KERNEL_CLAIM_SCOPE = "descriptive_conditional_response_not_causal_or_strategy_claim"
CANDIDATE_CLAIM_SCOPE = "candidate_model_diagnostic_not_causal_or_strategy_claim"
