use arrow_schema::{DataType, Field, Schema, TimeUnit};

/// Frozen table contract required as one complete snapshot closure.
pub(crate) struct TableSpec {
    pub(crate) name: &'static str,
    pub(crate) schema_id: &'static str,
    pub(crate) primary_key: &'static [&'static str],
}

impl TableSpec {
    pub(crate) fn schema(&self) -> Schema {
        schema(self.name)
    }
}

fn text(name: &str, nullable: bool) -> Field {
    Field::new(name, DataType::Utf8, nullable)
}
fn bytes(name: &str, nullable: bool) -> Field {
    Field::new(name, DataType::Binary, nullable)
}
fn int32(name: &str, nullable: bool) -> Field {
    Field::new(name, DataType::Int32, nullable)
}
fn int64(name: &str, nullable: bool) -> Field {
    Field::new(name, DataType::Int64, nullable)
}
fn boolean(name: &str, nullable: bool) -> Field {
    Field::new(name, DataType::Boolean, nullable)
}
fn instant(name: &str, nullable: bool) -> Field {
    Field::new(
        name,
        DataType::Timestamp(TimeUnit::Microsecond, Some("UTC".into())),
        nullable,
    )
}
fn atoms(name: &str, nullable: bool) -> Field {
    Field::new(name, DataType::Decimal128(20, 0), nullable)
}

#[allow(clippy::too_many_lines)]
fn schema(name: &str) -> Schema {
    let fields = match name {
        "scenes" => vec![
            text("scene_id", false),
            text("scene_mode", false),
            text("view_contract", false),
            text("view_contract_version", false),
            text("view_digest", false),
            text("source_mode", false),
            instant("rendered_at", false),
            instant("decision_available_at", false),
            int64("knowledge_commit_seq", false),
            int64("available_commit_seq", false),
        ],
        "territories" => vec![
            text("territory_id", false),
            text("territory_kind", false),
            text("description", false),
            instant("first_available_at", false),
            int64("available_commit_seq", false),
            text("source_assertion_id", false),
            text("source_observation_id", false),
        ],
        "candidates" => vec![
            text("candidate_id", false),
            text("mint_asset_id", false),
            text("territory_id", false),
            instant("created_at", false),
            instant("first_available_at", false),
            int64("available_commit_seq", false),
            text("source_assertion_id", false),
            text("source_observation_id", false),
        ],
        "candidate_social_assertions" => vec![
            text("social_assertion_id", false),
            text("candidate_id", false),
            text("identity_kind", false),
            text("identity_key", false),
            instant("event_time", false),
            instant("observed_at", false),
            instant("available_at", false),
            int64("available_commit_seq", false),
            text("source_assertion_id", false),
            text("source_observation_id", false),
        ],
        "decisions" => vec![
            text("decision_id", false),
            text("scene_id", false),
            text("choice_set_id", false),
            text("selected_candidate_id", true),
            text("episode_id", true),
            text("operator_action", false),
            text("selection_gesture_id", true),
            instant("decision_available_at", false),
            int64("available_commit_seq", false),
        ],
        "choice_members" => vec![
            text("choice_set_id", false),
            text("decision_id", false),
            text("scene_id", false),
            text("candidate_id", false),
            text("set_kind", false),
            int32("source_rank", true),
            int32("rendered_ordinal", true),
            boolean("in_viewport", false),
            boolean("interacted", false),
            text("evidence_assertion_id", true),
            text("evidence_observation_id", true),
            instant("available_at", false),
            int64("available_commit_seq", false),
        ],
        "episodes" => vec![
            text("episode_id", false),
            text("decision_id", false),
            text("candidate_id", false),
            text("territory_id", false),
            instant("opened_at", false),
            instant("closed_at", true),
            text("status", false),
            text("reentry_of_episode_id", true),
            text("operator_disposition", false),
            int64("available_commit_seq", false),
        ],
        "chart_samples" => vec![
            text("scene_id", false),
            text("scene_mode", false),
            text("scene_view_digest", false),
            text("decision_id", false),
            text("episode_id", false),
            text("candidate_id", false),
            text("territory_id", false),
            text("base_asset_id", false),
            text("quote_asset_id", false),
            int32("sample_index", false),
            int32("expected_sample_count", false),
            instant("event_time", false),
            instant("observed_at", false),
            instant("available_at", false),
            instant("decision_available_at", false),
            atoms("price_base_atoms", true),
            atoms("price_quote_atoms", true),
            atoms("buy_volume_base_atoms", true),
            atoms("sell_volume_base_atoms", true),
            text("position_state", false),
            text("coverage_status", false),
            text("coverage_scope_id", false),
            text("coverage_window_id", false),
            text("coverage_gap_id", true),
            text("source_assertion_id", true),
            text("source_observation_id", true),
            int64("available_commit_seq", false),
        ],
        "operator_gestures" => vec![
            text("gesture_id", false),
            text("decision_id", false),
            text("scene_id", false),
            text("scene_view_digest", false),
            text("candidate_id", false),
            text("episode_id", true),
            text("gesture_kind", false),
            instant("issued_at", false),
            instant("received_at", false),
            instant("available_at", false),
            text("command_payload_digest", false),
            int64("available_commit_seq", false),
        ],
        "operator_interviews" => vec![
            text("interview_id", false),
            text("decision_id", false),
            text("scene_id", false),
            text("episode_id", true),
            instant("elicited_at", false),
            instant("available_at", false),
            text("prompt_version", false),
            text("transcript_blob_id", false),
            text("operator_disposition", true),
            text("crackle_type", true),
            int32("confidence_ppm", true),
            boolean("outcome_visible_before_elicitation", false),
            int64("available_commit_seq", false),
        ],
        "outcomes" => vec![
            text("decision_id", false),
            text("candidate_id", false),
            text("episode_id", false),
            text("event_kind", true),
            instant("event_time", true),
            instant("outcome_known_at", false),
            instant("horizon_end", false),
            boolean("is_censored", false),
            text("censoring_reason", true),
            text("competing_risk_set", false),
            int64("available_commit_seq", false),
        ],
        "provenance_assertions" => vec![
            text("source_assertion_id", false),
            text("source_observation_id", false),
            text("source_id", false),
            text("semantic_key", false),
            text("value_digest", false),
            instant("observed_at", false),
            instant("available_at", false),
            int64("available_commit_seq", false),
        ],
        "coverage_windows" => vec![
            text("coverage_window_id", false),
            text("coverage_scope_id", false),
            text("source_id", false),
            instant("lower_time", false),
            instant("upper_time", false),
            text("coverage_kind", false),
            int64("available_commit_seq", false),
        ],
        "coverage_gaps" => vec![
            text("coverage_gap_id", false),
            text("coverage_window_id", false),
            text("coverage_scope_id", false),
            text("gap_class", false),
            instant("opened_at", false),
            instant("detected_at", false),
            instant("available_at", false),
            instant("recovered_at", true),
            instant("recovery_known_at", true),
            int64("available_commit_seq", false),
        ],
        "source_fact_occurrences" => vec![
            text("source_occurrence_id", false),
            text("run_registration_id", false),
            text("catalog_admission_id", false),
            text("source_id", false),
            text("receipt_digest", false),
            text("descriptor_contract", false),
            text("descriptor_digest", false),
            bytes("descriptor_bytes", false),
            int64("descriptor_byte_length", false),
            text("surface_profile_digest", false),
            int64("fact_count", false),
            int64("eligible_subject_count", false),
            int64("membership_count", false),
            int64("coverage_count", false),
            int64("gap_count", false),
            int64("rendered_subject_count", false),
            int64("omission_count", false),
            int64("hot_subject_count", false),
            int64("cold_control_subject_count", false),
            int64("known_through_commit_seq", false),
            instant("maximum_input_available_at", false),
            text("protection_class", false),
            text("authority", false),
            int64("available_commit_seq", false),
        ],
        "publication_occurrences" => vec![
            text("publication_id", false),
            text("preparation_id", false),
            text("source_occurrence_id", false),
            text("publication_contract", false),
            text("publication_digest", false),
            text("publication_bytes_digest", false),
            bytes("publication_bytes", false),
            int64("publication_byte_length", false),
            text("semantic_digest", false),
            text("container_digest", false),
            text("checkpoint_digest", false),
            int64("through_commit_seq", false),
            text("supersedes_publication_id", true),
            text("head_digest", false),
            bytes("head_bytes", false),
            int64("head_byte_length", false),
            text("supersedes_head_publication_id", true),
            text("authority", false),
            int64("publication_commit_seq", false),
            int64("available_commit_seq", false),
        ],
        "scene_occurrences" => vec![
            text("scene_publication_id", false),
            text("source_occurrence_id", false),
            text("publication_digest", false),
            bytes("publication_bytes", false),
            text("head_digest", false),
            bytes("head_bytes", false),
            text("supersedes_scene_publication_id", true),
            text("authority", false),
            int64("available_commit_seq", false),
        ],
        "act_occurrences" => vec![
            text("act_id", false),
            text("session_id", false),
            text("scene_publication_id", false),
            text("occurrence_digest", false),
            bytes("occurrence_bytes", false),
            int64("occurrence_byte_length", false),
            text("logical_start_tick", false),
            text("logical_end_tick", true),
            int64("queue_generation", false),
            text("qualification", false),
            text("authority", false),
            int64("available_commit_seq", false),
        ],
        "episode_occurrences" => vec![
            text("episode_id", false),
            text("session_id", false),
            text("scene_publication_id", false),
            text("opening_act_id", false),
            text("closing_act_id", true),
            text("occurrence_digest", false),
            bytes("occurrence_bytes", false),
            int64("occurrence_byte_length", false),
            text("logical_start_tick", false),
            text("logical_end_tick", true),
            int64("queue_generation", false),
            text("qualification", false),
            text("authority", false),
            int64("available_commit_seq", false),
        ],
        "run_occurrences" => vec![
            text("run_registration_id", false),
            text("registration_digest", false),
            int64("registration_byte_length", false),
            text("build_digest", false),
            text("source_tree_digest", false),
            text("configuration_digest", false),
            text("budget_digest", false),
            text("privacy_digest", false),
            text("daily_surface_profile_digest", false),
            text("authority", false),
            int64("available_commit_seq", false),
        ],
        "spool_catalog_occurrences" => vec![
            text("catalog_admission_id", false),
            text("run_registration_id", false),
            text("segment_id", false),
            text("batch_id", false),
            int64("store_commit_seq", false),
            text("binding_digest", false),
            int64("binding_byte_length", false),
            text("authority", false),
            int64("available_commit_seq", false),
        ],
        "status_occurrences" => vec![
            text("record_id", false),
            text("run_registration_id", false),
            text("component", false),
            text("record_kind", false),
            text("state", false),
            text("cause", true),
            text("predecessor_record_id", true),
            int64("evidence_commit_seq", true),
            instant("observed_at", false),
            text("detail_digest", true),
            text("record_digest", false),
            int64("record_byte_length", false),
            text("authority", false),
            int64("available_commit_seq", false),
        ],
        "export_occurrences" => vec![
            text("export_binding_id", false),
            text("run_registration_id", false),
            text("export_request_id", false),
            text("validation_id", false),
            text("snapshot_id", false),
            text("truth_fingerprint_digest", false),
            text("binding_digest", false),
            int64("binding_byte_length", false),
            text("authority", false),
            int64("available_commit_seq", false),
        ],
        "import_occurrences" => vec![
            text("import_id", false),
            text("run_registration_id", false),
            text("export_binding_id", false),
            text("export_request_id", false),
            text("analysis_run_id", false),
            text("artifact_id", false),
            text("artifact_contract", false),
            text("manifest_digest", false),
            bytes("manifest_bytes", false),
            int64("manifest_byte_length", false),
            text("snapshot_id", false),
            text("claim_scope", false),
            text("truth_fingerprint_digest", false),
            instant("maximum_input_available_at", false),
            text("registration_digest", false),
            int64("registration_byte_length", false),
            text("cas_physical_digest", false),
            int64("cas_byte_length", false),
            text("authority", false),
            int64("available_commit_seq", false),
        ],
        _ => unreachable!("frozen table name"),
    };
    Schema::new(fields)
}

pub(crate) const TABLE_SPECS: &[TableSpec] = &[
    TableSpec {
        name: "scenes",
        schema_id: "joshi.analysis.scene/v1",
        primary_key: &["scene_id"],
    },
    TableSpec {
        name: "territories",
        schema_id: "joshi.analysis.territory/v1",
        primary_key: &["territory_id"],
    },
    TableSpec {
        name: "candidates",
        schema_id: "joshi.analysis.candidate/v1",
        primary_key: &["candidate_id"],
    },
    TableSpec {
        name: "candidate_social_assertions",
        schema_id: "joshi.analysis.candidate-social-assertion/v1",
        primary_key: &["social_assertion_id"],
    },
    TableSpec {
        name: "decisions",
        schema_id: "joshi.analysis.decision/v1",
        primary_key: &["decision_id"],
    },
    TableSpec {
        name: "choice_members",
        schema_id: "joshi.analysis.choice-member/v1",
        primary_key: &["decision_id", "candidate_id", "set_kind"],
    },
    TableSpec {
        name: "episodes",
        schema_id: "joshi.analysis.episode/v1",
        primary_key: &["episode_id"],
    },
    TableSpec {
        name: "chart_samples",
        schema_id: "joshi.analysis.chart-sample/v1",
        primary_key: &["scene_id", "episode_id", "sample_index"],
    },
    TableSpec {
        name: "operator_gestures",
        schema_id: "joshi.analysis.operator-gesture/v1",
        primary_key: &["gesture_id"],
    },
    TableSpec {
        name: "operator_interviews",
        schema_id: "joshi.analysis.operator-interview/v1",
        primary_key: &["interview_id"],
    },
    TableSpec {
        name: "outcomes",
        schema_id: "joshi.analysis.competing-risk-outcome/v1",
        primary_key: &["decision_id", "candidate_id"],
    },
    TableSpec {
        name: "provenance_assertions",
        schema_id: "joshi.analysis.provenance-assertion/v1",
        primary_key: &["source_assertion_id", "source_observation_id"],
    },
    TableSpec {
        name: "coverage_windows",
        schema_id: "joshi.analysis.coverage-window/v1",
        primary_key: &["coverage_window_id"],
    },
    TableSpec {
        name: "coverage_gaps",
        schema_id: "joshi.analysis.coverage-gap/v1",
        primary_key: &["coverage_gap_id"],
    },
];

pub(crate) const G0_TABLE_SPECS: &[TableSpec] = &[
    TableSpec {
        name: "source_fact_occurrences",
        schema_id: "joshi.analysis.source-fact-occurrence/v1",
        primary_key: &["source_occurrence_id"],
    },
    TableSpec {
        name: "publication_occurrences",
        schema_id: "joshi.analysis.publication-occurrence/v1",
        primary_key: &["publication_id"],
    },
    TableSpec {
        name: "scene_occurrences",
        schema_id: "joshi.analysis.scene-occurrence/v1",
        primary_key: &["scene_publication_id"],
    },
    TableSpec {
        name: "act_occurrences",
        schema_id: "joshi.analysis.act-occurrence/v1",
        primary_key: &["act_id"],
    },
    TableSpec {
        name: "episode_occurrences",
        schema_id: "joshi.analysis.episode-occurrence/v1",
        primary_key: &["episode_id"],
    },
    TableSpec {
        name: "run_occurrences",
        schema_id: "joshi.analysis.run-occurrence/v1",
        primary_key: &["run_registration_id"],
    },
    TableSpec {
        name: "spool_catalog_occurrences",
        schema_id: "joshi.analysis.spool-catalog-occurrence/v1",
        primary_key: &["catalog_admission_id"],
    },
    TableSpec {
        name: "status_occurrences",
        schema_id: "joshi.analysis.status-occurrence/v1",
        primary_key: &["record_id"],
    },
    TableSpec {
        name: "export_occurrences",
        schema_id: "joshi.analysis.export-occurrence/v1",
        primary_key: &["export_binding_id"],
    },
    TableSpec {
        name: "import_occurrences",
        schema_id: "joshi.analysis.import-occurrence/v1",
        primary_key: &["import_id"],
    },
];
