"""Fixture-only known-truth and counterexample laboratory for Wave 6."""

from .lab import (
    AdversaryKind,
    CandidateDisposition,
    CandidateResult,
    KnownTruthCase,
    KnownTruthEvaluation,
    KnownTruthSuite,
    build_signed_flow_known_truth_suite,
    evaluate_candidate_suite,
)
from .protocol_battery import (
    DLMM_FIXTURE_DIGEST,
    PROTOCOL_BATTERY_AUTHORITY,
    PROTOCOL_BATTERY_SCHEMA,
    PUMP_FIXTURE_DIGEST,
    ProtocolAdversaryKind,
    ProtocolBatteryEvaluation,
    ProtocolCandidateResult,
    ProtocolCaseDisposition,
    ProtocolKnownTruthBattery,
    ProtocolTruthCase,
    build_protocol_known_truth_battery,
    evaluate_protocol_candidate,
    validate_protocol_candidate_result,
)

__all__ = [
    "DLMM_FIXTURE_DIGEST",
    "PROTOCOL_BATTERY_AUTHORITY",
    "PROTOCOL_BATTERY_SCHEMA",
    "PUMP_FIXTURE_DIGEST",
    "AdversaryKind",
    "CandidateDisposition",
    "CandidateResult",
    "KnownTruthCase",
    "KnownTruthEvaluation",
    "KnownTruthSuite",
    "ProtocolAdversaryKind",
    "ProtocolBatteryEvaluation",
    "ProtocolCandidateResult",
    "ProtocolCaseDisposition",
    "ProtocolKnownTruthBattery",
    "ProtocolTruthCase",
    "build_protocol_known_truth_battery",
    "build_signed_flow_known_truth_suite",
    "evaluate_candidate_suite",
    "evaluate_protocol_candidate",
    "validate_protocol_candidate_result",
]
