"""Bounded, proposal-only Wave 6 research desk."""

from .contracts import (
    AUTHORITY,
    CLAIM_SCOPE,
    SCHEMA_ID,
    ArtifactDescriptor,
    ArtifactRole,
    Control,
    CoverageStatus,
    DeskPolicy,
    DispositionKind,
    Estimand,
    ExperimentManifest,
    Falsifier,
    Feature,
    HumanDisposition,
    ProposalKind,
    ProposalRevision,
    ProposalSpec,
    ResearchProposal,
)
from .desk import ResearchDeskLedger, human_disposition, propose, supersession
from .fixture_packet import (
    FIXTURE_PACKET_AUTHORITY,
    FixtureProgramRegistration,
    FixtureResearchPacket,
    build_fixture_research_packet,
    parse_fixture_program_registration_exact,
)

__all__ = [
    "AUTHORITY",
    "CLAIM_SCOPE",
    "FIXTURE_PACKET_AUTHORITY",
    "SCHEMA_ID",
    "ArtifactDescriptor",
    "ArtifactRole",
    "Control",
    "CoverageStatus",
    "DeskPolicy",
    "DispositionKind",
    "Estimand",
    "ExperimentManifest",
    "Falsifier",
    "Feature",
    "FixtureProgramRegistration",
    "FixtureResearchPacket",
    "HumanDisposition",
    "ProposalKind",
    "ProposalRevision",
    "ProposalSpec",
    "ResearchDeskLedger",
    "ResearchProposal",
    "build_fixture_research_packet",
    "human_disposition",
    "parse_fixture_program_registration_exact",
    "propose",
    "supersession",
]
