/** Exact cross-language canonical bytes for the evidence-only operator command contract. */
export const GOLDEN_OPERATOR_PAYLOAD_V1_JSON = `{"context":{"uiLabel":"Record disposition","uiLabelVersion":"1","confidencePpm":"800000","urgency":"high","whyNow":"The tape changed.","note":"Might send; retain attention."},"disposition":"crackle then runner, provisional","provisional":true}`;

export const GOLDEN_OPERATOR_COMMAND_V1_JSON = `{"contract":"joshi.operator.command","schemaVersion":1,"commandId":"command-golden-1","idempotencyKey":"retry-golden-1","clientSessionId":"session-golden-1","clientCommandSeq":"7","scene":{"sceneId":"scene-golden-1","viewDigest":"sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"},"issuedAt":"2026-08-16T18:42:18.123456Z","clientClock":{"clockId":"clock-golden-1","monotonicNs":"99123"},"commandKind":"record_disposition","subject":{"kind":"candidate","key":"radon"},"payload":{"context":{"uiLabel":"Record disposition","uiLabelVersion":"1","confidencePpm":"800000","urgency":"high","whyNow":"The tape changed.","note":"Might send; retain attention."},"disposition":"crackle then runner, provisional","provisional":true},"authorityClass":"evidence_only","effectCeiling":"observe_only"}`;

export const GOLDEN_OPERATOR_PAYLOAD_V1_DIGEST = "sha256:11e7520b23cd385313fbdec6c5854614988ba4cdfadbe1958ca2078915233fa7";
export const GOLDEN_OPERATOR_COMMAND_V1_DIGEST = "sha256:7b27c7c0ceaee821a45b289c4694ced31d9a3861f1c59044335fd917a3abc531";

/** Exact W4 presentation-complete V2 vector. Rust admission must pin these bytes before claiming support. */
export const GOLDEN_OPERATOR_COMMAND_V2_JSON = `{"contract":"joshi.operator.command","schemaVersion":2,"commandId":"command-golden-2","idempotencyKey":"retry-golden-2","clientSessionId":"session-golden-1","clientCommandSeq":"8","scene":{"sceneId":"scene-golden-1","viewDigest":"sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"},"issuedAt":"2026-08-16T18:42:19.123456Z","clientClock":{"clockId":"clock-golden-1","monotonicNs":"100123"},"presentation":{"presentationId":"presentation-golden-1","presentationDigest":"sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb","assignmentId":"assignment-golden-1"},"cockpitPublication":{"cockpitPublicationId":"cockpit-golden-1","cockpitPublicationDigest":"sha256:cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"},"commandKind":"record_disposition","subject":{"kind":"candidate","key":"radon"},"payload":{"context":{"uiLabel":"Record disposition","uiLabelVersion":"1","confidencePpm":"800000","urgency":"high","whyNow":"The tape changed.","note":"Might send; retain attention."},"disposition":"crackle then runner, provisional","provisional":true},"authorityClass":"evidence_only","effectCeiling":"observe_only"}`;

export const GOLDEN_OPERATOR_COMMAND_V2_DIGEST = "sha256:c470a79010ac84b2a33d3027faa4695f337e848df7a52d84cf7d1da6c0e80fdb";
