/**
 * Exact TypeScript V1 presentation reference bytes. Every string is UTF-8 JSON without a trailing
 * newline. Digests are SHA-256 over the corresponding exact string, never over reparsed sender
 * JSON.
 */
export const GOLDEN_PRESENTATION_POLICY_V1_JSON = `{"contract":"joshi.presentation.policy","schemaVersion":1,"policyId":"policy-golden-v1","policyVersion":"1","title":"Golden flow-first policy","hypothesis":"Showing admitted flow beside explicit uncertainty may help without suppressing context.","assignmentMode":"operator_selected","primaryView":"wallet_cluster_flow","panelOrder":["attention-feed","hypothesis-lab","episode-rail","source-provenance"],"salience":[{"itemId":"hypothesis-lab","value":"prominent"},{"itemId":"source-provenance","value":"normal"}],"visibleOverlays":["observed","uncertain"],"safetyRules":{"neverOmitItemIds":["episode-rail","source-provenance"],"liveRandomization":"forbidden","informationPolicy":"preserve_rich_information"},"outcomes":[{"measure":"attention_cost","authority":"operator_report","note":"Operator report."},{"measure":"decision_latency","authority":"event_timestamps","note":"Derived from exact clocks."},{"measure":"missed_opportunity","authority":"choice_set_analysis","note":"Retrospective choice-set analysis."},{"measure":"overtrading","authority":"episode_analysis","note":"Reconciled episode analysis."},{"measure":"pnl","authority":"reconciled_accounting_projection","note":"Never computed in Glass."},{"measure":"regret","authority":"operator_report","note":"Operator report."}]}`;

export const GOLDEN_EXPLORATION_BUNDLE_V1_JSON = `{"contract":"joshi.presentation.exploration_bundle","schemaVersion":1,"bundleId":"exploration-golden-v1","scene":{"sceneId":"scene-golden-1","viewDigest":"sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"},"generatedAt":"2026-08-16T18:42:15.000000Z","claim":"descriptive_noncausal_fixture","sourceArtifacts":[{"artifactId":"artifact-golden-1","contract":"joshi.fixture.source_artifact","artifactDigest":"sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb","availableAt":"2026-08-16T18:42:15.000000Z","coverageBinding":"unverified_fixture","admissionStatus":"fixture_unverified"}],"panels":[{"panelId":"lab-attention-arrival","viewKind":"attention_arrival","title":"Attention arrival","question":"What arrived?","claimBoundary":"Fixture only.","evidenceClass":"uncertain","signals":[],"relations":[],"marks":[]},{"panelId":"lab-caller-response","viewKind":"caller_response_kernel","title":"Caller response","question":"What followed the mark?","claimBoundary":"Descriptive and noncausal.","evidenceClass":"derived","signals":[],"relations":[],"marks":[]},{"panelId":"lab-field-bundle","viewKind":"field_bundle","title":"Field bundle","question":"Where do fields disagree?","claimBoundary":"Not a pressure score.","evidenceClass":"mixed","signals":[],"relations":[],"marks":[]},{"panelId":"lab-lifecycle-topology","viewKind":"lifecycle_topology","title":"Lifecycle topology","question":"Which transitions coexist?","claimBoundary":"Transitions may overlap.","evidenceClass":"mixed","signals":[],"relations":[],"marks":[]},{"panelId":"lab-liquidity-resilience","viewKind":"liquidity_susceptibility_resilience","title":"Liquidity resilience","question":"How did marked response vary?","claimBoundary":"Not an executable quote.","evidenceClass":"derived","signals":[],"relations":[],"marks":[]},{"panelId":"lab-marked-orders","viewKind":"marked_order_timing_size","title":"Marked orders","question":"Where did observations land?","claimBoundary":"No intent is inferred.","evidenceClass":"observed","signals":[],"relations":[],"marks":[]},{"panelId":"lab-pvp-churn","viewKind":"pvp_compression_churn","title":"PvP churn","question":"Which directed edges changed?","claimBoundary":"No actor identity is inferred.","evidenceClass":"mixed","signals":[],"relations":[],"marks":[]},{"panelId":"lab-wallet-cluster-flow","viewKind":"wallet_cluster_flow","title":"Wallet flow","question":"Which actions are supported?","claimBoundary":"Clusters remain hypotheses.","evidenceClass":"mixed","signals":[],"relations":[],"marks":[]}]}`;

export const GOLDEN_PRESENTATION_POLICY_V1_DIGEST = "sha256:0dd7aa23c1eb08275436b88e5da0118a06acc482368b94ff2191447a8e8c468c";
export const GOLDEN_EXPLORATION_BUNDLE_V1_DIGEST = "sha256:f57c6cba14bb713dd09ee94e53eb5b26320c17a29c8ec2b4ac84d64afef17362";
export const GOLDEN_PRESENTATION_POLICY_V1_BYTES = 1285;
export const GOLDEN_EXPLORATION_BUNDLE_V1_BYTES = 2560;

export const GOLDEN_PRESENTATION_SCENE_V1_JSON = `{"contract":"joshi.presentation.scene","schemaVersion":1,"presentationId":"presentation-golden-1","idempotencyKey":"presentation-retry-golden-1","clientSessionId":"presentation-session-golden-1","presentationSeq":"1","scene":{"sceneId":"scene-golden-1","viewDigest":"sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"},"policy":{"policyId":"policy-golden-v1","policyVersion":"1","assignmentId":"manual-assignment-golden-1","policyDigest":"sha256:0dd7aa23c1eb08275436b88e5da0118a06acc482368b94ff2191447a8e8c468c"},"artifacts":[{"contract":"joshi.presentation.exploration_bundle","artifactId":"exploration-golden-v1","artifactDigest":"sha256:f57c6cba14bb713dd09ee94e53eb5b26320c17a29c8ec2b4ac84d64afef17362"}],"manifest":{"eligibleItemIds":["episode-rail","lab-field-bundle","lab-wallet-cluster-flow","source-provenance"],"selectedItemIds":["episode-rail","lab-wallet-cluster-flow","source-provenance"],"plannedRenderItemIds":["episode-rail","lab-wallet-cluster-flow","source-provenance"],"plannedInitialViewportItemIds":[],"items":[{"itemId":"episode-rail","itemKind":"shell_panel","placement":"right","ordinal":"0","visibility":"visible","omissionReason":null,"salience":"normal","pinned":false,"evidenceClass":"observed","safetyCritical":true},{"itemId":"lab-field-bundle","itemKind":"exploration_view","placement":"center","ordinal":"1","visibility":"omitted","omissionReason":"policy","salience":"normal","pinned":false,"evidenceClass":"mixed","safetyCritical":false},{"itemId":"lab-wallet-cluster-flow","itemKind":"exploration_view","placement":"center","ordinal":"0","visibility":"visible","omissionReason":null,"salience":"prominent","pinned":false,"evidenceClass":"mixed","safetyCritical":false},{"itemId":"source-provenance","itemKind":"shell_panel","placement":"right","ordinal":"1","visibility":"visible","omissionReason":null,"salience":"normal","pinned":false,"evidenceClass":"observed","safetyCritical":true}],"filters":[{"filterId":"evidence-class","value":"all"}],"toggles":[{"toggleId":"observed","state":true},{"toggleId":"uncertain","state":true}],"initialFocusItemId":null,"comparisonItemIds":[]},"capturedAt":"2026-08-16T18:42:15.000000Z","clientClock":{"clockId":"presentation-clock-golden-1","monotonicNs":"1000000"},"authorityClass":"evidence_only","effectCeiling":"observe_only"}`;

export const GOLDEN_PRESENTATION_SCENE_V1_DIGEST = "sha256:8c28191dd9b9714518a634c7fbdd97fa084cf10c8a76bc388dc127afc08d9df7";
export const GOLDEN_PRESENTATION_SCENE_V1_BYTES = 2325;

export const GOLDEN_PRESENTATION_EVENT_V1_JSON = `{"contract":"joshi.presentation.event","schemaVersion":1,"eventId":"presentation-event-golden-1","idempotencyKey":"presentation-event-retry-golden-1","clientSessionId":"presentation-session-golden-1","presentationEventSeq":"1","presentation":{"presentationId":"presentation-golden-1","presentationDigest":"sha256:8c28191dd9b9714518a634c7fbdd97fa084cf10c8a76bc388dc127afc08d9df7"},"scene":{"sceneId":"scene-golden-1","viewDigest":"sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"},"subject":{"kind":"panel","key":"lab-wallet-cluster-flow"},"occurredAt":"2026-08-16T18:42:15.100000Z","clientClock":{"clockId":"presentation-clock-golden-1","monotonicNs":"1100000"},"eventKind":"focus_started","payload":{"reason":"operator_navigation"},"authorityClass":"evidence_only","effectCeiling":"observe_only"}`;

export const GOLDEN_PRESENTATION_SCENE_RECEIPT_V1_JSON = `{"contract":"joshi.store.presentation_scene_receipt","schemaVersion":1,"catalogId":"catalog-golden-1","catalogSchema":"joshi.catalog.v1","batchId":"presentation-batch-golden-1","presentationId":"presentation-golden-1","idempotencyKey":"presentation-retry-golden-1","assignmentId":"manual-assignment-golden-1","scene":{"sceneId":"scene-golden-1","viewDigest":"sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"},"policyDigest":"sha256:0dd7aa23c1eb08275436b88e5da0118a06acc482368b94ff2191447a8e8c468c","presentationDigest":"sha256:8c28191dd9b9714518a634c7fbdd97fa084cf10c8a76bc388dc127afc08d9df7","commitSeq":"8001","status":"accepted"}`;

export const GOLDEN_PRESENTATION_EVENT_V1_DIGEST = "sha256:4fbd49185a10ee42be48a36f456b42c9e1126d079630c6e90d65b0a8b81dc30a";
export const GOLDEN_PRESENTATION_EVENT_V1_BYTES = 821;
export const GOLDEN_PRESENTATION_SCENE_RECEIPT_V1_DIGEST = "sha256:e5fc2454496191cd5a1db0744ddc14329509f0e1abb78c7bf5a01c7c2a01f171";
export const GOLDEN_PRESENTATION_SCENE_RECEIPT_V1_BYTES = 656;

export const GOLDEN_PRESENTATION_EVENT_RECEIPT_V1_JSON = `{"contract":"joshi.store.presentation_event_receipt","schemaVersion":1,"catalogId":"catalog-golden-1","catalogSchema":"joshi.catalog.v1","batchId":"presentation-event-batch-golden-1","eventId":"presentation-event-golden-1","presentation":{"presentationId":"presentation-golden-1","presentationDigest":"sha256:8c28191dd9b9714518a634c7fbdd97fa084cf10c8a76bc388dc127afc08d9df7"},"scene":{"sceneId":"scene-golden-1","viewDigest":"sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"},"eventDigest":"sha256:4fbd49185a10ee42be48a36f456b42c9e1126d079630c6e90d65b0a8b81dc30a","commitSeq":"8002","status":"accepted"}`;

export const GOLDEN_PRESENTATION_EVENT_RECEIPT_V1_DIGEST = "sha256:a5cff2d703c6a90114d4eeac56e9367958a64e787492e8b56280588d9364c422";
export const GOLDEN_PRESENTATION_EVENT_RECEIPT_V1_BYTES = 627;
